def gameCode():
    choicespeed(delay)
    print("")
    time.sleep(.2)
    textWriter(narrator[0], delay)
    time.sleep(1)
    textWriter(narrator[1], delay)
    time.sleep(1)
    textWriter(narrator[2], delay)
    time.sleep(1)
    choice = choiceworld(delay)
    print("")
    textWriter(narrator[11], delay)
    time.sleep(1)
    textWriter(narrator[12], delay)
    time.sleep(1)
    textWriter(narrator[13], delay)
    modifier = choicedifficulty(delay)
    time.sleep(1)